image: alpine/edge
packages:
  - go
sources:
  - https://github.com/ncastellani/imapServer
artifacts:
  - coverage.html
tasks:
  - build: |
      cd imapServer
      go build -race -v ./...
  - test: |
      cd imapServer
      go test -coverprofile=coverage.txt -covermode=atomic ./...
  - coverage: |
      cd imapServer
      go tool cover -html=coverage.txt -o ~/coverage.html
